"""Vietnamese text normalizer — restore diacritics from undiacritized OCR output.

Strategy:
- Multi-word phrases matched first (longest first) to avoid wrong single-word replacements
- Single words matched with word boundaries
- Case-preserving replacement
"""

import re

# ============================================================
# MULTI-WORD PHRASES  (matched first, longest first)
# ============================================================
_PHRASES: dict[str, str] = {
    # --- Admin / Government ---
    "uy ban nhan dan": "ủy ban nhân dân",
    "hoi dong nhan dan": "hội đồng nhân dân",
    "chu tich ubnd": "chủ tịch UBND",
    "pho chu tich": "phó chủ tịch",
    "chu tich": "chủ tịch",
    "cho tich": "chủ tịch",
    "cho tjch": "chủ tịch",
    "chu tjch": "chủ tịch",
    "chi tjch": "chủ tịch",
    "thu truong": "thủ trưởng",
    "the truong": "thủ trưởng",
    "tha truong": "thủ trưởng",
    "co quan": "cơ quan",
    "cor quan": "cơ quan",
    "cu quan": "cơ quan",
    "xi nghiep": "xí nghiệp",
    "xinghiep": "xí nghiệp",
    "xinghip": "xí nghiệp",
    "xac nhan": "xác nhận",
    "xac nhin": "xác nhận",
    "xie nhjn": "xác nhận",
    "xie nhin": "xác nhận",
    "xac minh": "xác minh",
    "bo noi vu": "bộ nội vụ",
    "bo tai chinh": "bộ tài chính",
    "bo giao duc": "bộ giáo dục",
    "bo y te": "bộ y tế",
    "bo cong an": "bộ công an",
    "bo quoc phong": "bộ quốc phòng",
    "bo ngoai giao": "bộ ngoại giao",
    "bo tu phap": "bộ tư pháp",
    "so ke hoach": "sở kế hoạch",
    "so tai chinh": "sở tài chính",
    "cong hoa xa hoi": "cộng hòa xã hội",
    "chu nghia": "chủ nghĩa",
    "doc lap": "độc lập",
    "tu do": "tự do",
    "hanh phuc": "hạnh phúc",
    "quoc hoi": "quốc hội",
    "chinh phu": "chính phủ",
    "thu tuong": "thủ tướng",
    "tong bi thu": "tổng bí thư",
    "dai bieu": "đại biểu",

    # --- Legal / Documents ---
    "khen thuong": "khen thưởng",
    "ky luat": "kỷ luật",
    "ky lujt": "kỷ luật",
    "cam doan": "cam đoan",
    "cam don": "cam đoan",
    "loi cam doan": "lời cam đoan",
    "loicamdoan": "lời cam đoan",
    "loi khai": "lời khai",
    "trach nhiem": "trách nhiệm",
    "trach nhim": "trách nhiệm",
    "hoan toan": "hoàn toàn",
    "hoan ton": "hoàn toàn",
    "su thuc": "sự thực",
    "su thyc": "sự thực",
    "giay chung nhan": "giấy chứng nhận",
    "giay phep": "giấy phép",
    "hop dong": "hợp đồng",
    "quyet dinh": "quyết định",
    "nghi dinh": "nghị định",
    "thong tu": "thông tư",
    "cong van": "công văn",
    "bien ban": "biên bản",
    "to trinh": "tờ trình",
    "bao cao": "báo cáo",
    "de nghi": "đề nghị",
    "phe duyet": "phê duyệt",
    "ban hanh": "ban hành",
    "hieu luc": "hiệu lực",
    "thi hanh": "thi hành",
    "chap hanh": "chấp hành",
    "vi pham": "vi phạm",
    "xu ly": "xử lý",
    "xu phat": "xử phạt",
    "khieu nai": "khiếu nại",
    "to cao": "tố cáo",
    "giai quyet": "giải quyết",
    "thu tuc": "thủ tục",
    "hanh chinh": "hành chính",
    "dan su": "dân sự",
    "hinh su": "hình sự",
    "kinh doanh": "kinh doanh",
    "dang ky": "đăng ký",
    "cap phep": "cấp phép",
    "chung thuc": "chứng thực",
    "cong chung": "công chứng",
    "ho khau": "hộ khẩu",
    "tam tru": "tạm trú",
    "thuong tru": "thường trú",
    "can cuoc": "căn cước",
    "chung minh": "chứng minh",
    "nhan dan": "nhân dân",
    "the can cuoc": "thẻ căn cước",

    # --- Education ---
    "hoc thac sy": "học thạc sỹ",
    "hoe thac sy": "học thạc sỹ",
    "hoc thac si": "học thạc sĩ",
    "tien si": "tiến sĩ",
    "thac si": "thạc sĩ",
    "thac sy": "thạc sỹ",
    "cu nhan": "cử nhân",
    "ky su": "kỹ sư",
    "dai hoc": "đại học",
    "cao dang": "cao đẳng",
    "trung cap": "trung cấp",
    "nghien cuu sinh": "nghiên cứu sinh",
    "nghien cuu": "nghiên cứu",
    "nghien ciru": "nghiên cứu",
    "nghien ciu": "nghiên cứu",
    "giao duc": "giáo dục",
    "dao tao": "đào tạo",
    "tot nghiep": "tốt nghiệp",
    "bang cap": "bằng cấp",
    "chung chi": "chứng chỉ",
    "hoc bong": "học bổng",

    # --- Work / Organization ---
    "nong nghiep": "nông nghiệp",
    "nong nghip": "nông nghiệp",
    "trung tam": "trung tâm",
    "trung tin": "trung tâm",
    "trung tim": "trung tâm",
    "tu van": "tư vấn",
    "tur van": "tư vấn",
    "tur vin": "tư vấn",
    "lam viec": "làm việc",
    "lam vie": "làm việc",
    "lam viee": "làm việc",
    "lam vice": "làm việc",
    "xa hoi": "xã hội",
    "xi hoi": "xã hội",
    "cong ty": "công ty",
    "doanh nghiep": "doanh nghiệp",
    "to chuc": "tổ chức",
    "co phan": "cổ phần",
    "trach nhiem huu han": "trách nhiệm hữu hạn",
    "nha nuoc": "nhà nước",
    "tu nhan": "tư nhân",
    "nhan vien": "nhân viên",
    "can bo": "cán bộ",
    "cong chuc": "công chức",
    "vien chuc": "viên chức",
    "chuyen vien": "chuyên viên",
    "giam doc": "giám đốc",
    "pho giam doc": "phó giám đốc",
    "truong phong": "trưởng phòng",
    "pho phong": "phó phòng",
    "ke toan": "kế toán",
    "thu ky": "thư ký",
    "nhan su": "nhân sự",
    "luong co ban": "lương cơ bản",
    "bao hiem": "bảo hiểm",
    "bao hiem xa hoi": "bảo hiểm xã hội",
    "bao hiem y te": "bảo hiểm y tế",
    "nghi viec": "nghỉ việc",
    "nghi phep": "nghỉ phép",
    "tang luong": "tăng lương",
    "bo nhiem": "bổ nhiệm",
    "mien nhiem": "miễn nhiệm",
    "chuyen cong tac": "chuyển công tác",
    "dieu dong": "điều động",
    "hop dong lao dong": "hợp đồng lao động",

    # --- Person / Identity ---
    "nguoi khai": "người khai",
    "ngubi khai": "người khai",
    "nguoi khni": "người khai",
    "ky ten": "ký tên",
    "ky tin": "ký tên",
    "ho va ten": "họ và tên",
    "ho ten": "họ tên",
    "ngay sinh": "ngày sinh",
    "noi sinh": "nơi sinh",
    "gioi tinh": "giới tính",
    "que quan": "quê quán",
    "dan toc": "dân tộc",
    "ton giao": "tôn giáo",
    "quoc tich": "quốc tịch",
    "dia chi": "địa chỉ",
    "so dien thoai": "số điện thoại",
    "nghe nghiep": "nghề nghiệp",
    "trinh do": "trình độ",
    "chuyen mon": "chuyên môn",

    # --- Finance ---
    "tai chinh": "tài chính",
    "ngan sach": "ngân sách",
    "thue thu nhap": "thuế thu nhập",
    "hoa don": "hóa đơn",
    "chi phi": "chi phí",
    "doanh thu": "doanh thu",
    "loi nhuan": "lợi nhuận",
    "von dau tu": "vốn đầu tư",
    "dau tu": "đầu tư",
    "ke hoach": "kế hoạch",
    "ngan hang": "ngân hàng",
    "tai khoan": "tài khoản",
    "tien mat": "tiền mặt",
    "chuyen khoan": "chuyển khoản",

    # --- Health ---
    "benh vien": "bệnh viện",
    "phong kham": "phòng khám",
    "bac si": "bác sĩ",
    "benh nhan": "bệnh nhân",
    "kham benh": "khám bệnh",
    "dieu tri": "điều trị",
    "thuoc men": "thuốc men",
    "suc khoe": "sức khỏe",

    # --- Location ---
    "thanh pho": "thành phố",
    "thi xa": "thị xã",
    "thi tran": "thị trấn",
    "huyen": "huyện",
    "phuong": "phường",
    "ha noi": "Hà Nội",
    "ho chi minh": "Hồ Chí Minh",
    "da nang": "Đà Nẵng",
    "hai phong": "Hải Phòng",
    "can tho": "Cần Thơ",
    "viet nam": "Việt Nam",
}

# ============================================================
# SINGLE WORDS
# ============================================================
_SINGLES: dict[str, str] = {
    # --- Time ---
    "thang": "tháng", "thing": "tháng",
    "nam": "năm",
    "ngay": "ngày",
    "gio": "giờ",
    "phut": "phút",
    "giay": "giây",
    "tuan": "tuần",

    # --- Pronouns / Common ---
    "toi": "tôi",
    "ban": "bạn",
    "anh": "anh",
    "chi": "chị",
    "em": "em",
    "ong": "ông",
    "ba": "bà",
    "chung": "chúng",
    "ho": "họ",
    "minh": "mình",
    "ai": "ai",

    # --- Verbs ---
    "lam": "làm",
    "xin": "xin",
    "hoc": "học", "hoe": "học",
    "lam": "làm",
    "biet": "biết",
    "noi": "nói",
    "nghe": "nghe",
    "doc": "đọc",
    "viet": "viết",
    "xem": "xem",
    "den": "đến",
    "di": "đi",
    "ve": "về",
    "o": "ở",
    "co": "có",
    "khong": "không",
    "duoc": "được",
    "phai": "phải",
    "can": "cần",
    "nen": "nên",
    "muon": "muốn",
    "thay": "thấy",
    "nghi": "nghĩ",
    "hieu": "hiểu",
    "yeu": "yêu",
    "giu": "giữ",
    "cho": "cho",
    "lay": "lấy",
    "dat": "đặt",
    "gui": "gửi",
    "nhan": "nhận", "nhin": "nhận", "nhjn": "nhận",
    "tra": "trả",
    "mua": "mua",
    "ban": "bán",
    "doi": "đổi",
    "tang": "tăng",
    "giam": "giảm",
    "them": "thêm",
    "bot": "bớt",
    "bat": "bắt",
    "dau": "đầu",
    "ket": "kết",
    "thuc": "thực",
    "hien": "hiện",
    "tiep": "tiếp",
    "tuc": "tục",
    "sinh": "sinh",
    "song": "sống",
    "chet": "chết",
    "mo": "mở",
    "dong": "đóng",
    "nop": "nộp",
    "cap": "cấp",
    "ky": "ký", "ki": "ký",

    # --- Adjectives ---
    "tot": "tốt",
    "xau": "xấu",
    "dep": "đẹp",
    "lon": "lớn",
    "nho": "nhỏ",
    "cao": "cao",
    "thap": "thấp",
    "dai": "dài",
    "ngan": "ngắn",
    "rong": "rộng",
    "hep": "hẹp",
    "moi": "mới",
    "cu": "cũ",
    "tre": "trẻ",
    "gia": "già",
    "dung": "đúng", "dng": "đúng",
    "sai": "sai",
    "chinh": "chính",
    "phu": "phụ",
    "quan": "quan",
    "trong": "trọng",

    # --- Nouns ---
    "nguoi": "người", "ngubi": "người",
    "nuoc": "nước",
    "nha": "nhà",
    "truong": "trường",
    "benh": "bệnh",
    "vien": "viện", "vin": "viện",
    "viec": "việc", "vie": "việc", "viee": "việc", "vice": "việc",
    "so": "số",
    "ten": "tên", "tin": "tên",
    "dia": "địa",
    "tinh": "tỉnh",
    "tich": "tịch",
    "phuong": "phường", "phurng": "phường", "phumg": "phường",
    "pho": "phó",
    "xa": "xã",
    "nong": "nông",
    "nghiep": "nghiệp", "nghip": "nghiệp",
    "nghien": "nghiên",
    "nhiem": "nhiệm", "nhim": "nhiệm",
    "thuong": "thưởng",
    "thu": "thủ", "tha": "thủ",
    "thi": "thị",
    "chinh": "chính",
    "chiu": "chịu",
    "chu": "chủ",
    "cuu": "cứu", "ciru": "cứu", "ciu": "cứu",
    "luat": "luật", "lut": "luật", "lujt": "luật",
    "doan": "đoan",
    "dieu": "điều", "diu": "điều",
    "hoan": "hoàn",
    "hoi": "hội",
    "khen": "khen",
    "khai": "khai", "khni": "khai",
    "xac": "xác", "xie": "xác",
    "loi": "lời",
    "lan": "lần",
    "sach": "sách", "sich": "sách",
    "neu": "nếu",
    "ton": "toàn",
    "bo": "bộ",
    "cua": "của",
    "la": "là",
    "tren": "trên",
    "nhung": "những", "nhng": "những", "nng": "những",
    "gi": "gì",
    "nao": "nào",
    "ma": "mà",
    "vi": "vì",
    "va": "và",
    "hay": "hay",
    "hoac": "hoặc",
    "nhung": "nhưng",
    "neu": "nếu",
    "thi": "thì",
    "da": "đã",
    "dang": "đang",
    "se": "sẽ",
    "roi": "rồi",
    "chua": "chưa",
    "con": "còn",
    "het": "hết",
    "nua": "nữa",
    "luon": "luôn",
    "cung": "cũng",
    "chi": "chỉ",
    "rat": "rất",
    "qua": "quá",
    # "lam": "lắm",  # ambiguous with "làm"
    "nhat": "nhất",
    "moi": "mọi",
    "tat": "tất",
    "ca": "cả",
    "tung": "từng",
    "tong": "tổng",
    "rieng": "riêng",
    "chung": "chung",

    # --- Names (common Vietnamese family/given names) ---
    "luong": "lương",
    "ngoc": "ngọc", "ngoe": "ngọc",
    "ha": "hà",
    "hong": "hồng",
    "son": "sơn",
    "huong": "hương",
    "thao": "thảo",
    "trang": "trang",
    "lan": "lan",
    "mai": "mai",
    "hoa": "hoa",
    "phuong": "phương",
    "linh": "linh",
    "hang": "hằng",
    "hanh": "hạnh",
    "dung": "dũng",
    "duc": "đức",
    "tuan": "tuấn",
    "hung": "hùng",
    "thanh": "thành",
    "minh": "minh",
    "quang": "quang",
    "hieu": "hiếu",
    "long": "long",
    "nam": "nam",
    "binh": "bình",
    "cuong": "cường",
    "dat": "đạt",
    "tai": "tài",
    "phuc": "phúc",
    "loc": "lộc",
    "tho": "thọ",
    "nguyen": "nguyễn",
    "tran": "trần",
    "le": "lê",
    "pham": "phạm",
    "huynh": "huỳnh",
    "hoang": "hoàng",
    "phan": "phan",
    "vu": "vũ",
    "dang": "đặng",
    "bui": "bùi",
    "do": "đỗ",
    "ngo": "ngô",
    "duong": "dương",
    "ly": "lý",
    "dinh": "đinh",
    "trinh": "trịnh",
    "truong": "trương",
}

# Sort phrases by length (longest first)
_PHRASE_PATTERNS = sorted(_PHRASES.keys(), key=len, reverse=True)


def _apply_case(original: str, replacement: str) -> str:
    """Preserve the casing pattern of the original text."""
    if original.isupper():
        return replacement.upper()
    if original[0].isupper():
        return replacement[0].upper() + replacement[1:]
    return replacement


def _replace_word(match: re.Match) -> str:
    word = match.group(0)
    lower = word.lower()
    replacement = _SINGLES.get(lower)
    if replacement is None:
        return word
    return _apply_case(word, replacement)


# Pre-compile the single-word pattern
_singles_sorted = sorted(_SINGLES.keys(), key=len, reverse=True)
_WORD_PATTERN = re.compile(
    r'\b(' + '|'.join(re.escape(w) for w in _singles_sorted) + r')\b',
    re.IGNORECASE
)


def normalize_vietnamese(text: str) -> str:
    """Attempt to restore Vietnamese diacritics from Latin OCR output."""
    # 1. Replace multi-word phrases first (longest first)
    for phrase in _PHRASE_PATTERNS:
        pattern = re.compile(re.escape(phrase), re.IGNORECASE)
        repl = _PHRASES[phrase]
        text = pattern.sub(lambda m, r=repl: _apply_case(m.group(0), r), text)

    # 2. Replace single words (word boundary aware)
    text = _WORD_PATTERN.sub(_replace_word, text)

    return text
